modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}"

license="${mod_license}"
issueTrackerURL="https://github.com/florian-berger/indestructible-tools/issues"


[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="indestructibletools.png"

displayURL="https://berger-media.biz/downloads/10/minecraft/indestructible-tools"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    # the modid of the dependency
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
