modLoader="javafml" #mandatory

loaderVersion="[38,)"

license="https://github.com/florian-berger/indestructible-tools/blob/master/LICENSE"
issueTrackerURL="https://github.com/florian-berger/indestructible-tools/issues"


[[mods]]
modId="indestructibletools"
version="2021.2.1"
displayName="Indestructible Tools"
logoFile="indestructibletools.png"

displayURL="https://berger-media.biz/downloads/10/minecraft/indestructible-tools"
authors="Florian <UltimateG4ming> Berger" #optional
description='''
This mod is adding some indestructible tools to Minecraft. They are crafted by using indestructible ingots, that are created from diamonds, iron ingots and netherite ingots.
'''

[[dependencies.indestructibletools]]
    # the modid of the dependency
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.indestructibletools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18)"
    ordering="NONE"
    side="BOTH"
