name: "Bug Report"
description: "File a bug report if something goes wrong."
title: "[Bug]: "
labels: ["bug"]
assignees:
  - florian-berger

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! It is helpful to fill all of the fields below.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can I get in touch with you if I need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue as detailed as you can remember.
      placeholder: Tell me what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Please describe the steps that are required to reproduce the issue
      placeholder: Tell me how to reproduce!
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What Minecraft version are you playing?
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of the mod are you using?
    validations:
      required: true

  - type: textarea
    id: other-mods
    attributes:
      label: Other mods
      description: Please give a list of other installed mods.

  - type: textarea
    id: further-data
    attributes:
      label: Further information / Screenshots / Logs
      description: |
        If you have any further information, screenshots, or log files, you can enter them here. 
        To attach images, click this area to highlight it and then drag your files into it.
    validations:
      required: false